apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote
  labels:
    app: vote
spec:
  selector:
    app: vote
  ports:
    - port: 5000
      targetPort: 8080
      name: vote
  type: LoadBalancer