apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: IMAGE_REPO:VERSION
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
            requests:
              cpu: 50m
              memory: 50M
            limits:
              cpu: "250m"
              memory: "250M"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
